site_name: Wye Make Documentation
site_url: https://docs.wyemake.co.uk/
theme:
    name: material
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
